[project]
name = "marin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Subhamoy Datta", email = "subhamoydatta99@gmail.com" }
]
requires-python = ">=3.12,<3.14"
dependencies = [
    "numpy>=2.5.3",
    "scipy>=1.18.1",
    "sounddevice>=0.5.6",
    "torch>=2.14.0",
    "torchaudio>=2.11.0",
    "transformers>=5.17.0",
    "google-genai>=1.29.0",
    "pydantic>=2.13.5",
    "kokoro>=0.9.4",
    "rich>=15.0.0",
    "edge-tts>=7.2.8",
    "pydub>=0.25.1",
    "python-dotenv>=1.2.3",
    "accelerate>=1.15.0",
    "soundfile>=0.14.0",
    "torchaudio>=2.11.0",
    "funasr>=1.4.16",
    "modelscope>=1.40.1",
    "onnxruntime>=1.30.0",
]

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
torchaudio = { index = "pytorch-cu126" }

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true


[project.scripts]
marin = "marin:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"
